import React, { useContext, useState } from "react";
import ItemsContext from "../../contexts/ItemsContext";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function itemId({ item }) {
	const items = useContext(ItemsContext);
	const [message, setMessage] = useState();
	return (
		<>
			<Head>
				<title>{item}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{message ? (
				<h1 className={styles.message} onClick={() => setMessage()}>
					{message}
				</h1>
			) : (
				""
			)}
			{Object.keys(items).includes(item) ? (
				<div className={styles.item}>
					<h1>{item}</h1>
					<img src={items[item].image} />
					<h3>{items[item].cost}$</h3>
					<button
						className={styles.button}
						onClick={async (e) => {
							await fetch("/cartAdd", {
								headers: {
									Accept: "application/json",
									"Content-Type": "application/json",
								},
								method: "POST",
								body: JSON.stringify({ item }),
							});
							setMessage((await addItem.json()).message);
							setTimeout(() => setMessage(), 1000);
						}}
					>
						Add to cart
					</button>
				</div>
			) : (
				<h1>Could not find item</h1>
			)}
		</>
	);
}

export function getServerSideProps(context) {
	return {
		props: { item: context.params.id },
	};
}
