import React, { useContext, useState } from "react";
import ItemsContext from "../contexts/ItemsContext";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ cartLength }) {
	const items = useContext(ItemsContext);
	const [message, setMessage] = useState();
	return (
		<div className={styles.grid}>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{message ? (
				<h1 className={styles.message} onClick={() => setMessage()}>
					{message}
				</h1>
			) : (
				""
			)}
			{Object.keys(items).map((item, i) => {
				return (
					<div key={i} className={styles.gridItem}>
						<img src={items[item].image} />
						<a href={`/item/${item}`}>
							<h3>{item}</h3>
						</a>
						<p>{items[item].cost}$</p>
						<button
							onClick={async (e) => {
								const addItem = await fetch("/cartAdd", {
									headers: {
										Accept: "application/json",
										"Content-Type": "application/json",
									},
									method: "POST",
									body: JSON.stringify({ item }),
								});
								setMessage((await addItem.json()).message);
								setTimeout(() => setMessage(), 1000);
							}}
						>
							Add to cart
						</button>
					</div>
				);
			})}
		</div>
	);
}

export function getServerSideProps(context) {
	return {
		props: { cartLength: context.req.cartLength || 0 },
	};
}
